export const KENYA_COUNTIES = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;

export type KenyaCounty = (typeof KENYA_COUNTIES)[number];

export const KENYA_REGIONS: Record<string, readonly KenyaCounty[]> = {
  Central: ["Kiambu", "Kirinyaga", "Murang'a", "Nyandarua", "Nyeri"],
  Coast: ["Kilifi", "Kwale", "Lamu", "Mombasa", "Taita-Taveta", "Tana River"],
  Eastern: ["Embu", "Isiolo", "Kitui", "Machakos", "Makueni", "Marsabit", "Meru", "Tharaka-Nithi"],
  Nairobi: ["Nairobi"],
  "North Eastern": ["Garissa", "Mandera", "Wajir"],
  Nyanza: ["Homa Bay", "Kisii", "Kisumu", "Migori", "Nyamira", "Siaya"],
  "Rift Valley": [
    "Baringo",
    "Bomet",
    "Elgeyo-Marakwet",
    "Kajiado",
    "Kericho",
    "Laikipia",
    "Nakuru",
    "Nandi",
    "Narok",
    "Samburu",
    "Trans Nzoia",
    "Turkana",
    "Uasin Gishu",
    "West Pokot",
  ],
  Western: ["Bungoma", "Busia", "Kakamega", "Vihiga"],
};

export function kenyaRegionForCounty(county: string): string | null {
  return (
    Object.entries(KENYA_REGIONS).find(([, counties]) =>
      counties.some((candidate) => candidate.toLowerCase() === county.trim().toLowerCase()),
    )?.[0] ?? null
  );
}
